// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8V9qrjc4oXPHN5fO1_r1ieSAKDp0S_KY',
    appId: '1:706491407166:web:f1e908d7d3406570036a6f',
    messagingSenderId: '706491407166',
    projectId: 'rutasegura-a74f7',
    authDomain: 'rutasegura-a74f7.firebaseapp.com',
    storageBucket: 'rutasegura-a74f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdvkAygHbD0LlsX2WIjwii26iLUWDX0iw',
    appId: '1:706491407166:android:01fedb49515310b2036a6f',
    messagingSenderId: '706491407166',
    projectId: 'rutasegura-a74f7',
    storageBucket: 'rutasegura-a74f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGYVUsw033XbCn2f5EEEd3LumOCkJQTdM',
    appId: '1:706491407166:ios:71b936c1ce94a78c036a6f',
    messagingSenderId: '706491407166',
    projectId: 'rutasegura-a74f7',
    storageBucket: 'rutasegura-a74f7.firebasestorage.app',
    iosBundleId: 'com.rutasegura.rutaSegura',
  );
}
